
// This file was auto-generated by ML.NET Model Builder. 

using PredictiveMaintenanceModel_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
PredictiveMaintenanceModel.ModelInput sampleData = new PredictiveMaintenanceModel.ModelInput()
{
    Product_ID = @"L47181",
    Type = @"L",
    Air_temperature = 298.2F,
    Process_temperature = 308.7F,
    Rotational_speed = 1408F,
    Torque = 46.3F,
    Tool_wear = 3F,
};

// Make a single prediction on the sample data and print results
var predictionResult = PredictiveMaintenanceModel.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Machine_failure with predicted Machine_failure from sample data...\n\n");


Console.WriteLine($"Product_ID: {@"L47181"}");
Console.WriteLine($"Type: {@"L"}");
Console.WriteLine($"Air_temperature: {298.2F}");
Console.WriteLine($"Process_temperature: {308.7F}");
Console.WriteLine($"Rotational_speed: {1408F}");
Console.WriteLine($"Torque: {46.3F}");
Console.WriteLine($"Tool_wear: {3F}");
Console.WriteLine($"Machine_failure: {0F}");


Console.WriteLine($"\n\nPredicted Machine_failure: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

